[theme]
# Primary accent color for interactive elements
primaryColor = "#d33682"

# Background Color for main content area
backgroundColor = "#ffffff"

# Background Color used for sidebar and most interactive widgets
secondaryBackgroundColor = "#586e75"

# Color for all text
textColor = "#000000"